global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "api:8080"

  - job_name: "vllm"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "vllm:8000"

  - job_name: "dcgm-exporter"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "dcgm-exporter:9400"